package parser

import (
	"strings"
	"testing"
)

// ---- helpers ----------------------------------------------------------------

func mustParse(t *testing.T, sql string) Statement {
	t.Helper()
	stmt, err := Parse(sql)
	if err != nil {
		t.Fatalf("Parse(%q) error: %v", sql, err)
	}
	return stmt
}

func ptr(s string) *string { return &s }

// ---- CREATE TABLE -----------------------------------------------------------

func TestParseCreateTable_Simple(t *testing.T) {
	stmt := mustParse(t, "CREATE TABLE users (id bigint, name text)")
	ct, ok := stmt.(CreateTableStmt)
	if !ok {
		t.Fatalf("want CreateTableStmt, got %T", stmt)
	}
	if ct.TableName != "users" {
		t.Errorf("TableName: got %q, want %q", ct.TableName, "users")
	}
	if len(ct.Columns) != 2 {
		t.Fatalf("Columns len: got %d, want 2", len(ct.Columns))
	}
	if ct.Columns[0].Name != "id" || ct.Columns[0].DataType != "bigint" {
		t.Errorf("col0: %+v", ct.Columns[0])
	}
}

func TestParseCreateTable_IfNotExists(t *testing.T) {
	stmt := mustParse(t, "CREATE TABLE IF NOT EXISTS t (id int)")
	ct := stmt.(CreateTableStmt)
	if ct.TableName != "t" {
		t.Errorf("TableName: got %q, want %q", ct.TableName, "t")
	}
}

func TestParseCreateTable_NotNullAndDefault(t *testing.T) {
	stmt := mustParse(t, "CREATE TABLE t (n int NOT NULL DEFAULT 0)")
	ct := stmt.(CreateTableStmt)
	col := ct.Columns[0]
	if !col.NotNull {
		t.Error("expected NotNull=true")
	}
	if col.Default == nil || *col.Default != "0" {
		t.Errorf("Default: got %v", col.Default)
	}
}

func TestParseCreateTable_GeneratedStored(t *testing.T) {
	stmt := mustParse(t, `CREATE TABLE t (
		id   bigint,
		full_name text GENERATED ALWAYS AS (first || ' ' || last) STORED
	)`)
	ct := stmt.(CreateTableStmt)
	if len(ct.Columns) != 2 {
		t.Fatalf("expected 2 columns, got %d", len(ct.Columns))
	}
	gen := ct.Columns[1]
	if gen.Name != "full_name" {
		t.Errorf("Name: got %q", gen.Name)
	}
	if gen.DataType != "text" {
		t.Errorf("DataType: got %q", gen.DataType)
	}
	if len(gen.InlineConstraints) == 0 {
		t.Fatal("InlineConstraints should contain GENERATED clause")
	}
	if !strings.Contains(strings.ToUpper(gen.InlineConstraints[0]), "GENERATED ALWAYS AS") {
		t.Errorf("InlineConstraints[0]: got %q", gen.InlineConstraints[0])
	}
}

func TestParseCreateTable_GeneratedIdentity(t *testing.T) {
	for _, sql := range []string{
		"CREATE TABLE t (id bigint GENERATED ALWAYS AS IDENTITY)",
		"CREATE TABLE t (id bigint GENERATED BY DEFAULT AS IDENTITY)",
	} {
		stmt := mustParse(t, sql)
		ct := stmt.(CreateTableStmt)
		col := ct.Columns[0]
		if col.DataType != "bigint" {
			t.Errorf("DataType: got %q for: %s", col.DataType, sql)
		}
		if len(col.InlineConstraints) == 0 {
			t.Errorf("InlineConstraints empty for: %s", sql)
		}
		upper := strings.ToUpper(col.InlineConstraints[0])
		if !strings.Contains(upper, "GENERATED") || !strings.Contains(upper, "AS IDENTITY") {
			t.Errorf("InlineConstraints[0]=%q for: %s", col.InlineConstraints[0], sql)
		}
	}
}

// --- Table structure options -------------------------------------------------

// INHERITS, WITH, TABLESPACE, PARTITION BY are silently ignored (come after
// the closing paren). We just verify no parse error occurs.
func TestParseCreateTable_TrailingOptionsIgnored(t *testing.T) {
	cases := []string{
		`CREATE TABLE child (extra text) INHERITS (parent)`,
		`CREATE TABLE t (id int) WITH (fillfactor=70)`,
		`CREATE TABLE t (id int) TABLESPACE pg_default`,
		`CREATE TABLE measurement (city_id int, logdate date) PARTITION BY RANGE (logdate)`,
	}
	for _, sql := range cases {
		if _, err := Parse(sql); err != nil {
			t.Errorf("unexpected error for %q: %v", sql, err)
		}
	}
}

// LIKE clause inside parens is preserved verbatim as a TableConstraint.
func TestParseCreateTable_LikeClause(t *testing.T) {
	stmt := mustParse(t, `CREATE TABLE t2 (LIKE t1 INCLUDING ALL, extra text)`)
	ct := stmt.(CreateTableStmt)
	if len(ct.Constraints) != 1 {
		t.Fatalf("expected 1 constraint (LIKE clause), got %d; cols=%v", len(ct.Constraints), ct.Columns)
	}
	upper := strings.ToUpper(ct.Constraints[0].Definition)
	if !strings.Contains(upper, "LIKE T1") || !strings.Contains(upper, "INCLUDING ALL") {
		t.Errorf("Constraints[0].Definition: got %q", ct.Constraints[0].Definition)
	}
	// extra column should still be parsed
	if len(ct.Columns) != 1 || ct.Columns[0].Name != "extra" {
		t.Errorf("expected column 'extra', got %v", ct.Columns)
	}
}

func TestParseCreateTable_CheckNoInherit(t *testing.T) {
	stmt := mustParse(t, `CREATE TABLE t (val int CHECK (val > 0) NO INHERIT)`)
	ct := stmt.(CreateTableStmt)
	col := ct.Columns[0]
	if len(col.InlineConstraints) == 0 {
		t.Fatal("InlineConstraints should contain CHECK NO INHERIT")
	}
	upper := strings.ToUpper(col.InlineConstraints[0])
	if !strings.Contains(upper, "CHECK") || !strings.Contains(upper, "NO INHERIT") {
		t.Errorf("InlineConstraints[0]: got %q", col.InlineConstraints[0])
	}
}

func TestParseCreateTable_FKDetails(t *testing.T) {
	stmt := mustParse(t, `CREATE TABLE t (
		user_id int REFERENCES users(id) ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY DEFERRED,
		CONSTRAINT fk_team FOREIGN KEY (user_id) REFERENCES teams(id) MATCH FULL ON DELETE SET NULL NOT DEFERRABLE
	)`)
	ct := stmt.(CreateTableStmt)

	// inline FK with ON DELETE / ON UPDATE / DEFERRABLE
	col := ct.Columns[0]
	if len(col.InlineConstraints) == 0 {
		t.Fatal("InlineConstraints should contain FK clause")
	}
	upper := strings.ToUpper(col.InlineConstraints[0])
	for _, kw := range []string{"ON DELETE CASCADE", "ON UPDATE RESTRICT", "DEFERRABLE", "INITIALLY DEFERRED"} {
		if !strings.Contains(upper, kw) {
			t.Errorf("missing %q in InlineConstraints: %s", kw, col.InlineConstraints[0])
		}
	}

	// named FK with MATCH FULL / ON DELETE / NOT DEFERRABLE
	if len(ct.Constraints) != 1 {
		t.Fatalf("expected 1 table constraint, got %d", len(ct.Constraints))
	}
	def := strings.ToUpper(ct.Constraints[0].Definition)
	for _, kw := range []string{"MATCH FULL", "ON DELETE SET NULL", "NOT DEFERRABLE"} {
		if !strings.Contains(def, kw) {
			t.Errorf("missing %q in constraint def: %s", kw, ct.Constraints[0].Definition)
		}
	}
}

func TestParseCreateTable_ExcludeConstraint(t *testing.T) {
	stmt := mustParse(t, `CREATE TABLE reservation (
		room_id int,
		during tsrange,
		EXCLUDE USING gist (room_id WITH =, during WITH &&)
	)`)
	ct := stmt.(CreateTableStmt)
	if len(ct.Constraints) != 1 {
		t.Fatalf("expected 1 constraint, got %d: cols=%v", len(ct.Constraints), ct.Columns)
	}
	upper := strings.ToUpper(ct.Constraints[0].Definition)
	if !strings.Contains(upper, "EXCLUDE") || !strings.Contains(upper, "USING GIST") {
		t.Errorf("Constraints[0].Definition: got %q", ct.Constraints[0].Definition)
	}
}

func TestParseCreateTable_UniqueNullsDistinct(t *testing.T) {
	stmt := mustParse(t, `CREATE TABLE t (
		id int,
		a  int,
		UNIQUE NULLS NOT DISTINCT (a),
		UNIQUE NULLS DISTINCT (id, a)
	)`)
	ct := stmt.(CreateTableStmt)
	if len(ct.Constraints) != 2 {
		t.Fatalf("expected 2 constraints, got %d", len(ct.Constraints))
	}
	upper0 := strings.ToUpper(ct.Constraints[0].Definition)
	if !strings.Contains(upper0, "UNIQUE NULLS NOT DISTINCT") {
		t.Errorf("Constraints[0].Definition: got %q", ct.Constraints[0].Definition)
	}
	upper1 := strings.ToUpper(ct.Constraints[1].Definition)
	if !strings.Contains(upper1, "UNIQUE NULLS DISTINCT") {
		t.Errorf("Constraints[1].Definition: got %q", ct.Constraints[1].Definition)
	}
}

func TestParseCreateTable_CompressionAndStorage(t *testing.T) {
	stmt := mustParse(t, `CREATE TABLE t (
		data bytea COMPRESSION lz4,
		body text STORAGE EXTENDED
	)`)
	ct := stmt.(CreateTableStmt)
	if len(ct.Columns) != 2 {
		t.Fatalf("expected 2 columns, got %d", len(ct.Columns))
	}

	data := ct.Columns[0]
	if data.DataType != "bytea" {
		t.Errorf("data.DataType: got %q", data.DataType)
	}
	if len(data.InlineConstraints) == 0 || !strings.Contains(strings.ToUpper(data.InlineConstraints[0]), "COMPRESSION") {
		t.Errorf("data.InlineConstraints: got %v", data.InlineConstraints)
	}

	body := ct.Columns[1]
	if body.DataType != "text" {
		t.Errorf("body.DataType: got %q", body.DataType)
	}
	if len(body.InlineConstraints) == 0 || !strings.Contains(strings.ToUpper(body.InlineConstraints[0]), "STORAGE") {
		t.Errorf("body.InlineConstraints: got %v", body.InlineConstraints)
	}
}

func TestParseCreateTable_Collate(t *testing.T) {
	stmt := mustParse(t, `CREATE TABLE t (name text COLLATE "ja-x-icu" NOT NULL, code text COLLATE pg_catalog.default)`)
	ct := stmt.(CreateTableStmt)
	if len(ct.Columns) != 2 {
		t.Fatalf("expected 2 columns, got %d", len(ct.Columns))
	}

	name := ct.Columns[0]
	if name.DataType != "text" {
		t.Errorf("name.DataType: got %q", name.DataType)
	}
	if name.Collation != `"ja-x-icu"` {
		t.Errorf("name.Collation: got %q", name.Collation)
	}
	if !name.NotNull {
		t.Error("name.NotNull should be true")
	}

	code := ct.Columns[1]
	if code.Collation != "pg_catalog.default" {
		t.Errorf("code.Collation: got %q", code.Collation)
	}
}

func TestParseCreateTable_ExplicitNull(t *testing.T) {
	stmt := mustParse(t, "CREATE TABLE t (id int NULL, name text NOT NULL)")
	ct := stmt.(CreateTableStmt)
	id := ct.Columns[0]
	if id.DataType != "int" {
		t.Errorf("DataType: got %q, want %q", id.DataType, "int")
	}
	if id.NotNull {
		t.Error("id.NotNull should be false")
	}
	name := ct.Columns[1]
	if !name.NotNull {
		t.Error("name.NotNull should be true")
	}
}

func TestParseCreateTable_Temporary(t *testing.T) {
	for _, sql := range []string{
		"CREATE TEMPORARY TABLE tmp (id int)",
		"CREATE TEMP TABLE tmp (id int)",
	} {
		stmt := mustParse(t, sql)
		ct := stmt.(CreateTableStmt)
		if ct.TableName != "tmp" {
			t.Errorf("TableName: got %q", ct.TableName)
		}
		if !ct.Temporary {
			t.Errorf("Temporary should be true for: %s", sql)
		}
		if ct.Unlogged {
			t.Errorf("Unlogged should be false for: %s", sql)
		}
	}
}

func TestParseCreateTable_Unlogged(t *testing.T) {
	stmt := mustParse(t, "CREATE UNLOGGED TABLE logs (id int)")
	ct := stmt.(CreateTableStmt)
	if ct.TableName != "logs" {
		t.Errorf("TableName: got %q", ct.TableName)
	}
	if ct.Temporary {
		t.Error("Temporary should be false")
	}
	if !ct.Unlogged {
		t.Error("Unlogged should be true")
	}
}

func TestParseCreateTable_TemporaryIfNotExists(t *testing.T) {
	stmt := mustParse(t, "CREATE TEMPORARY TABLE IF NOT EXISTS tmp (id int)")
	ct := stmt.(CreateTableStmt)
	if ct.TableName != "tmp" || !ct.Temporary {
		t.Errorf("got %+v", ct)
	}
}

func TestParseCreateTable_WithConstraint(t *testing.T) {
	stmt := mustParse(t, "CREATE TABLE t (id int, CONSTRAINT pk PRIMARY KEY (id))")
	ct := stmt.(CreateTableStmt)
	if len(ct.Constraints) != 1 {
		t.Fatalf("Constraints len: got %d, want 1", len(ct.Constraints))
	}
	if ct.Constraints[0].Name != "pk" {
		t.Errorf("constraint name: got %q", ct.Constraints[0].Name)
	}
}

// ---- ALTER TABLE ------------------------------------------------------------

func TestParseAlterTable_AddColumn(t *testing.T) {
	stmt := mustParse(t, "ALTER TABLE t ADD COLUMN email text")
	at := stmt.(AlterTableStmt)
	if at.TableName != "t" {
		t.Errorf("TableName: got %q", at.TableName)
	}
	if len(at.Actions) != 1 {
		t.Fatalf("Actions len: got %d", len(at.Actions))
	}
	a := at.Actions[0]
	if a.Kind != ActionAddColumn {
		t.Errorf("Kind: got %v", a.Kind)
	}
	if a.ColDef == nil || a.ColDef.DataType != "text" {
		t.Errorf("ColDef: %+v", a.ColDef)
	}
}

func TestParseAlterTable_DropColumn(t *testing.T) {
	stmt := mustParse(t, "ALTER TABLE t DROP COLUMN old_col")
	at := stmt.(AlterTableStmt)
	a := at.Actions[0]
	if a.Kind != ActionDropColumn || a.Column != "old_col" {
		t.Errorf("action: %+v", a)
	}
}

func TestParseAlterTable_AlterColumnType(t *testing.T) {
	stmt := mustParse(t, "ALTER TABLE t ALTER COLUMN price TYPE numeric(10,2)")
	at := stmt.(AlterTableStmt)
	a := at.Actions[0]
	if a.Kind != ActionAlterColumnType {
		t.Errorf("Kind: got %v", a.Kind)
	}
	if a.DataType != "numeric(10,2)" {
		t.Errorf("DataType: got %q", a.DataType)
	}
}

func TestParseAlterTable_SetDefault(t *testing.T) {
	stmt := mustParse(t, "ALTER TABLE t ALTER COLUMN status SET DEFAULT 'active'")
	at := stmt.(AlterTableStmt)
	a := at.Actions[0]
	if a.Kind != ActionSetDefault || a.Default != "'active'" {
		t.Errorf("action: %+v", a)
	}
}

func TestParseAlterTable_DropDefault(t *testing.T) {
	stmt := mustParse(t, "ALTER TABLE t ALTER COLUMN status DROP DEFAULT")
	at := stmt.(AlterTableStmt)
	a := at.Actions[0]
	if a.Kind != ActionDropDefault {
		t.Errorf("Kind: got %v", a.Kind)
	}
}

func TestParseAlterTable_SetNotNull(t *testing.T) {
	stmt := mustParse(t, "ALTER TABLE t ALTER COLUMN name SET NOT NULL")
	at := stmt.(AlterTableStmt)
	if at.Actions[0].Kind != ActionSetNotNull {
		t.Errorf("Kind: got %v", at.Actions[0].Kind)
	}
}

func TestParseAlterTable_DropNotNull(t *testing.T) {
	stmt := mustParse(t, "ALTER TABLE t ALTER COLUMN name DROP NOT NULL")
	at := stmt.(AlterTableStmt)
	if at.Actions[0].Kind != ActionDropNotNull {
		t.Errorf("Kind: got %v", at.Actions[0].Kind)
	}
}

func TestParseAlterTable_RenameColumn(t *testing.T) {
	stmt := mustParse(t, "ALTER TABLE t RENAME COLUMN old TO new")
	at := stmt.(AlterTableStmt)
	a := at.Actions[0]
	if a.Kind != ActionRenameColumn || a.Column != "old" || a.NewName != "new" {
		t.Errorf("action: %+v", a)
	}
}

func TestParseAlterTable_RenameTo(t *testing.T) {
	stmt := mustParse(t, "ALTER TABLE t RENAME TO t2")
	at := stmt.(AlterTableStmt)
	a := at.Actions[0]
	if a.Kind != ActionRenameTo || a.NewName != "t2" {
		t.Errorf("action: %+v", a)
	}
}

func TestParseAlterTable_AddConstraint(t *testing.T) {
	stmt := mustParse(t, "ALTER TABLE t ADD CONSTRAINT fk FOREIGN KEY (uid) REFERENCES users(id)")
	at := stmt.(AlterTableStmt)
	a := at.Actions[0]
	if a.Kind != ActionAddConstraint || a.Constraint.Name != "fk" {
		t.Errorf("action: %+v", a)
	}
}

func TestParseAlterTable_DropConstraint(t *testing.T) {
	stmt := mustParse(t, "ALTER TABLE t DROP CONSTRAINT fk")
	at := stmt.(AlterTableStmt)
	a := at.Actions[0]
	if a.Kind != ActionDropConstraint || a.Constraint.Name != "fk" {
		t.Errorf("action: %+v", a)
	}
}

func TestParseAlterTable_MultipleActions(t *testing.T) {
	stmt := mustParse(t, "ALTER TABLE t ADD COLUMN a int, ADD COLUMN b text")
	at := stmt.(AlterTableStmt)
	if len(at.Actions) != 2 {
		t.Fatalf("Actions len: got %d, want 2", len(at.Actions))
	}
}

// ---- DROP TABLE -------------------------------------------------------------

func TestParseDropTable(t *testing.T) {
	stmt := mustParse(t, "DROP TABLE users")
	dt := stmt.(DropTableStmt)
	if dt.TableName != "users" || dt.IfExists {
		t.Errorf("%+v", dt)
	}
}

func TestParseDropTable_IfExists(t *testing.T) {
	stmt := mustParse(t, "DROP TABLE IF EXISTS users")
	dt := stmt.(DropTableStmt)
	if !dt.IfExists {
		t.Error("expected IfExists=true")
	}
}

// ---- CREATE INDEX -----------------------------------------------------------

func TestParseCreateIndex(t *testing.T) {
	stmt := mustParse(t, "CREATE INDEX idx_email ON users (email)")
	ci := stmt.(CreateIndexStmt)
	if ci.IndexName != "idx_email" || ci.TableName != "users" || ci.Unique {
		t.Errorf("%+v", ci)
	}
}

func TestParseCreateUniqueIndex(t *testing.T) {
	stmt := mustParse(t, "CREATE UNIQUE INDEX idx_email ON users (email)")
	ci := stmt.(CreateIndexStmt)
	if !ci.Unique {
		t.Error("expected Unique=true")
	}
}

func TestParseCreateIndex_Concurrently(t *testing.T) {
	stmt := mustParse(t, "CREATE INDEX CONCURRENTLY idx_name ON t (name)")
	ci := stmt.(CreateIndexStmt)
	if ci.IndexName != "idx_name" {
		t.Errorf("IndexName: %q", ci.IndexName)
	}
}

// ---- DROP INDEX -------------------------------------------------------------

func TestParseDropIndex(t *testing.T) {
	stmt := mustParse(t, "DROP INDEX idx_email")
	di := stmt.(DropIndexStmt)
	if di.IndexName != "idx_email" || di.IfExists {
		t.Errorf("%+v", di)
	}
}

func TestParseDropIndex_IfExists(t *testing.T) {
	stmt := mustParse(t, "DROP INDEX IF EXISTS idx_email")
	di := stmt.(DropIndexStmt)
	if !di.IfExists {
		t.Error("expected IfExists=true")
	}
}

// ---- CREATE SEQUENCE --------------------------------------------------------

func TestParseCreateSequence(t *testing.T) {
	stmt := mustParse(t, "CREATE SEQUENCE users_id_seq START 1")
	cs := stmt.(CreateSequenceStmt)
	if cs.SeqName != "users_id_seq" {
		t.Errorf("SeqName: %q", cs.SeqName)
	}
	if !strings.Contains(cs.Body, "START 1") {
		t.Errorf("Body: %q", cs.Body)
	}
}

// ---- DROP SEQUENCE ----------------------------------------------------------

func TestParseDropSequence(t *testing.T) {
	stmt := mustParse(t, "DROP SEQUENCE users_id_seq")
	ds := stmt.(DropSequenceStmt)
	if ds.SeqName != "users_id_seq" || ds.IfExists {
		t.Errorf("%+v", ds)
	}
}

func TestParseDropSequence_IfExists(t *testing.T) {
	stmt := mustParse(t, "DROP SEQUENCE IF EXISTS users_id_seq")
	ds := stmt.(DropSequenceStmt)
	if !ds.IfExists {
		t.Error("expected IfExists=true")
	}
}

// ---- CREATE TYPE ------------------------------------------------------------

func TestParseCreateTypeEnum(t *testing.T) {
	stmt := mustParse(t, "CREATE TYPE status AS ENUM ('active', 'inactive', 'pending')")
	ct := stmt.(CreateTypeStmt)
	if ct.TypeName != "status" {
		t.Errorf("TypeName: %q", ct.TypeName)
	}
	if len(ct.Labels) != 3 {
		t.Fatalf("Labels len: got %d, want 3", len(ct.Labels))
	}
	if ct.Labels[0] != "active" {
		t.Errorf("Labels[0]: %q", ct.Labels[0])
	}
}

func TestParseCreateTypeNonEnum_FallsBackToUnknown(t *testing.T) {
	stmt := mustParse(t, "CREATE TYPE address AS (street text, city text)")
	if _, ok := stmt.(UnknownStmt); !ok {
		t.Errorf("want UnknownStmt, got %T", stmt)
	}
}

// ---- Unknown ----------------------------------------------------------------

func TestParseUnknown(t *testing.T) {
	stmt := mustParse(t, "SET search_path = public")
	u, ok := stmt.(UnknownStmt)
	if !ok {
		t.Fatalf("want UnknownStmt, got %T", stmt)
	}
	if u.Raw != "SET search_path = public" {
		t.Errorf("Raw: %q", u.Raw)
	}
}
