package parser

import (
	"strings"
	"testing"
)

// ---- helpers ----------------------------------------------------------------

func mustParse(t *testing.T, sql string) Statement {
	t.Helper()
	stmt, err := Parse(sql)
	if err != nil {
		t.Fatalf("Parse(%q) error: %v", sql, err)
	}
	return stmt
}

func ptr(s string) *string { return &s }

// ---- CREATE TABLE -----------------------------------------------------------

func TestParseCreateTable_Simple(t *testing.T) {
	stmt := mustParse(t, "CREATE TABLE users (id bigint, name text)")
	ct, ok := stmt.(CreateTableStmt)
	if !ok {
		t.Fatalf("want CreateTableStmt, got %T", stmt)
	}
	if ct.TableName != "users" {
		t.Errorf("TableName: got %q, want %q", ct.TableName, "users")
	}
	if len(ct.Columns) != 2 {
		t.Fatalf("Columns len: got %d, want 2", len(ct.Columns))
	}
	if ct.Columns[0].Name != "id" || ct.Columns[0].DataType != "bigint" {
		t.Errorf("col0: %+v", ct.Columns[0])
	}
}

func TestParseCreateTable_IfNotExists(t *testing.T) {
	stmt := mustParse(t, "CREATE TABLE IF NOT EXISTS t (id int)")
	ct := stmt.(CreateTableStmt)
	if ct.TableName != "t" {
		t.Errorf("TableName: got %q, want %q", ct.TableName, "t")
	}
}

func TestParseCreateTable_NotNullAndDefault(t *testing.T) {
	stmt := mustParse(t, "CREATE TABLE t (n int NOT NULL DEFAULT 0)")
	ct := stmt.(CreateTableStmt)
	col := ct.Columns[0]
	if !col.NotNull {
		t.Error("expected NotNull=true")
	}
	if col.Default == nil || *col.Default != "0" {
		t.Errorf("Default: got %v", col.Default)
	}
}

func TestParseCreateTable_GeneratedStored(t *testing.T) {
	stmt := mustParse(t, `CREATE TABLE t (
		id   bigint,
		full_name text GENERATED ALWAYS AS (first || ' ' || last) STORED
	)`)
	ct := stmt.(CreateTableStmt)
	if len(ct.Columns) != 2 {
		t.Fatalf("expected 2 columns, got %d", len(ct.Columns))
	}
	gen := ct.Columns[1]
	if gen.Name != "full_name" {
		t.Errorf("Name: got %q", gen.Name)
	}
	if gen.DataType != "text" {
		t.Errorf("DataType: got %q", gen.DataType)
	}
	if len(gen.InlineConstraints) == 0 {
		t.Fatal("InlineConstraints should contain GENERATED clause")
	}
	if !strings.Contains(strings.ToUpper(gen.InlineConstraints[0]), "GENERATED ALWAYS AS") {
		t.Errorf("InlineConstraints[0]: got %q", gen.InlineConstraints[0])
	}
}

func TestParseCreateTable_GeneratedIdentity(t *testing.T) {
	for _, sql := range []string{
		"CREATE TABLE t (id bigint GENERATED ALWAYS AS IDENTITY)",
		"CREATE TABLE t (id bigint GENERATED BY DEFAULT AS IDENTITY)",
	} {
		stmt := mustParse(t, sql)
		ct := stmt.(CreateTableStmt)
		col := ct.Columns[0]
		if col.DataType != "bigint" {
			t.Errorf("DataType: got %q for: %s", col.DataType, sql)
		}
		if len(col.InlineConstraints) == 0 {
			t.Errorf("InlineConstraints empty for: %s", sql)
		}
		upper := strings.ToUpper(col.InlineConstraints[0])
		if !strings.Contains(upper, "GENERATED") || !strings.Contains(upper, "AS IDENTITY") {
			t.Errorf("InlineConstraints[0]=%q for: %s", col.InlineConstraints[0], sql)
		}
	}
}

// --- Table structure options -------------------------------------------------

// INHERITS, WITH, TABLESPACE, PARTITION BY are silently ignored (come after
// the closing paren). We just verify no parse error occurs.
func TestParseCreateTable_TrailingOptionsIgnored(t *testing.T) {
	cases := []string{
		`CREATE TABLE child (extra text) INHERITS (parent)`,
		`CREATE TABLE t (id int) WITH (fillfactor=70)`,
		`CREATE TABLE t (id int) TABLESPACE pg_default`,
		`CREATE TABLE measurement (city_id int, logdate date) PARTITION BY RANGE (logdate)`,
	}
	for _, sql := range cases {
		if _, err := Parse(sql); err != nil {
			t.Errorf("unexpected error for %q: %v", sql, err)
		}
	}
}

// LIKE clause inside parens is preserved verbatim as a TableConstraint.
func TestParseCreateTable_LikeClause(t *testing.T) {
	stmt := mustParse(t, `CREATE TABLE t2 (LIKE t1 INCLUDING ALL, extra text)`)
	ct := stmt.(CreateTableStmt)
	if len(ct.Constraints) != 1 {
		t.Fatalf("expected 1 constraint (LIKE clause), got %d; cols=%v", len(ct.Constraints), ct.Columns)
	}
	upper := strings.ToUpper(ct.Constraints[0].Definition)
	if !strings.Contains(upper, "LIKE T1") || !strings.Contains(upper, "INCLUDING ALL") {
		t.Errorf("Constraints[0].Definition: got %q", ct.Constraints[0].Definition)
	}
	// extra column should still be parsed
	if len(ct.Columns) != 1 || ct.Columns[0].Name != "extra" {
		t.Errorf("expected column 'extra', got %v", ct.Columns)
	}
}

func TestParseCreateTable_CheckNoInherit(t *testing.T) {
	stmt := mustParse(t, `CREATE TABLE t (val int CHECK (val > 0) NO INHERIT)`)
	ct := stmt.(CreateTableStmt)
	col := ct.Columns[0]
	if len(col.InlineConstraints) == 0 {
		t.Fatal("InlineConstraints should contain CHECK NO INHERIT")
	}
	upper := strings.ToUpper(col.InlineConstraints[0])
	if !strings.Contains(upper, "CHECK") || !strings.Contains(upper, "NO INHERIT") {
		t.Errorf("InlineConstraints[0]: got %q", col.InlineConstraints[0])
	}
}

func TestParseCreateTable_FKDetails(t *testing.T) {
	stmt := mustParse(t, `CREATE TABLE t (
		user_id int REFERENCES users(id) ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY DEFERRED,
		CONSTRAINT fk_team FOREIGN KEY (user_id) REFERENCES teams(id) MATCH FULL ON DELETE SET NULL NOT DEFERRABLE
	)`)
	ct := stmt.(CreateTableStmt)

	// inline FK with ON DELETE / ON UPDATE / DEFERRABLE
	col := ct.Columns[0]
	if len(col.InlineConstraints) == 0 {
		t.Fatal("InlineConstraints should contain FK clause")
	}
	upper := strings.ToUpper(col.InlineConstraints[0])
	for _, kw := range []string{"ON DELETE CASCADE", "ON UPDATE RESTRICT", "DEFERRABLE", "INITIALLY DEFERRED"} {
		if !strings.Contains(upper, kw) {
			t.Errorf("missing %q in InlineConstraints: %s", kw, col.InlineConstraints[0])
		}
	}

	// named FK with MATCH FULL / ON DELETE / NOT DEFERRABLE
	if len(ct.Constraints) != 1 {
		t.Fatalf("expected 1 table constraint, got %d", len(ct.Constraints))
	}
	def := strings.ToUpper(ct.Constraints[0].Definition)
	for _, kw := range []string{"MATCH FULL", "ON DELETE SET NULL", "NOT DEFERRABLE"} {
		if !strings.Contains(def, kw) {
			t.Errorf("missing %q in constraint def: %s", kw, ct.Constraints[0].Definition)
		}
	}
}

func TestParseCreateTable_ExcludeConstraint(t *testing.T) {
	stmt := mustParse(t, `CREATE TABLE reservation (
		room_id int,
		during tsrange,
		EXCLUDE USING gist (room_id WITH =, during WITH &&)
	)`)
	ct := stmt.(CreateTableStmt)
	if len(ct.Constraints) != 1 {
		t.Fatalf("expected 1 constraint, got %d: cols=%v", len(ct.Constraints), ct.Columns)
	}
	upper := strings.ToUpper(ct.Constraints[0].Definition)
	if !strings.Contains(upper, "EXCLUDE") || !strings.Contains(upper, "USING GIST") {
		t.Errorf("Constraints[0].Definition: got %q", ct.Constraints[0].Definition)
	}
}

func TestParseCreateTable_UniqueNullsDistinct(t *testing.T) {
	stmt := mustParse(t, `CREATE TABLE t (
		id int,
		a  int,
		UNIQUE NULLS NOT DISTINCT (a),
		UNIQUE NULLS DISTINCT (id, a)
	)`)
	ct := stmt.(CreateTableStmt)
	if len(ct.Constraints) != 2 {
		t.Fatalf("expected 2 constraints, got %d", len(ct.Constraints))
	}
	upper0 := strings.ToUpper(ct.Constraints[0].Definition)
	if !strings.Contains(upper0, "UNIQUE NULLS NOT DISTINCT") {
		t.Errorf("Constraints[0].Definition: got %q", ct.Constraints[0].Definition)
	}
	upper1 := strings.ToUpper(ct.Constraints[1].Definition)
	if !strings.Contains(upper1, "UNIQUE NULLS DISTINCT") {
		t.Errorf("Constraints[1].Definition: got %q", ct.Constraints[1].Definition)
	}
}

func TestParseCreateTable_CompressionAndStorage(t *testing.T) {
	stmt := mustParse(t, `CREATE TABLE t (
		data bytea COMPRESSION lz4,
		body text STORAGE EXTENDED
	)`)
	ct := stmt.(CreateTableStmt)
	if len(ct.Columns) != 2 {
		t.Fatalf("expected 2 columns, got %d", len(ct.Columns))
	}

	data := ct.Columns[0]
	if data.DataType != "bytea" {
		t.Errorf("data.DataType: got %q", data.DataType)
	}
	if len(data.InlineConstraints) == 0 || !strings.Contains(strings.ToUpper(data.InlineConstraints[0]), "COMPRESSION") {
		t.Errorf("data.InlineConstraints: got %v", data.InlineConstraints)
	}

	body := ct.Columns[1]
	if body.DataType != "text" {
		t.Errorf("body.DataType: got %q", body.DataType)
	}
	if len(body.InlineConstraints) == 0 || !strings.Contains(strings.ToUpper(body.InlineConstraints[0]), "STORAGE") {
		t.Errorf("body.InlineConstraints: got %v", body.InlineConstraints)
	}
}

func TestParseCreateTable_Collate(t *testing.T) {
	stmt := mustParse(t, `CREATE TABLE t (name text COLLATE "ja-x-icu" NOT NULL, code text COLLATE pg_catalog.default)`)
	ct := stmt.(CreateTableStmt)
	if len(ct.Columns) != 2 {
		t.Fatalf("expected 2 columns, got %d", len(ct.Columns))
	}

	name := ct.Columns[0]
	if name.DataType != "text" {
		t.Errorf("name.DataType: got %q", name.DataType)
	}
	if name.Collation != `"ja-x-icu"` {
		t.Errorf("name.Collation: got %q", name.Collation)
	}
	if !name.NotNull {
		t.Error("name.NotNull should be true")
	}

	code := ct.Columns[1]
	if code.Collation != "pg_catalog.default" {
		t.Errorf("code.Collation: got %q", code.Collation)
	}
}

func TestParseCreateTable_ExplicitNull(t *testing.T) {
	stmt := mustParse(t, "CREATE TABLE t (id int NULL, name text NOT NULL)")
	ct := stmt.(CreateTableStmt)
	id := ct.Columns[0]
	if id.DataType != "int" {
		t.Errorf("DataType: got %q, want %q", id.DataType, "int")
	}
	if id.NotNull {
		t.Error("id.NotNull should be false")
	}
	name := ct.Columns[1]
	if !name.NotNull {
		t.Error("name.NotNull should be true")
	}
}

func TestParseCreateTable_Temporary(t *testing.T) {
	for _, sql := range []string{
		"CREATE TEMPORARY TABLE tmp (id int)",
		"CREATE TEMP TABLE tmp (id int)",
	} {
		stmt := mustParse(t, sql)
		ct := stmt.(CreateTableStmt)
		if ct.TableName != "tmp" {
			t.Errorf("TableName: got %q", ct.TableName)
		}
		if !ct.Temporary {
			t.Errorf("Temporary should be true for: %s", sql)
		}
		if ct.Unlogged {
			t.Errorf("Unlogged should be false for: %s", sql)
		}
	}
}

func TestParseCreateTable_Unlogged(t *testing.T) {
	stmt := mustParse(t, "CREATE UNLOGGED TABLE logs (id int)")
	ct := stmt.(CreateTableStmt)
	if ct.TableName != "logs" {
		t.Errorf("TableName: got %q", ct.TableName)
	}
	if ct.Temporary {
		t.Error("Temporary should be false")
	}
	if !ct.Unlogged {
		t.Error("Unlogged should be true")
	}
}

func TestParseCreateTable_TemporaryIfNotExists(t *testing.T) {
	stmt := mustParse(t, "CREATE TEMPORARY TABLE IF NOT EXISTS tmp (id int)")
	ct := stmt.(CreateTableStmt)
	if ct.TableName != "tmp" || !ct.Temporary {
		t.Errorf("got %+v", ct)
	}
}

func TestParseCreateTable_WithConstraint(t *testing.T) {
	stmt := mustParse(t, "CREATE TABLE t (id int, CONSTRAINT pk PRIMARY KEY (id))")
	ct := stmt.(CreateTableStmt)
	if len(ct.Constraints) != 1 {
		t.Fatalf("Constraints len: got %d, want 1", len(ct.Constraints))
	}
	if ct.Constraints[0].Name != "pk" {
		t.Errorf("constraint name: got %q", ct.Constraints[0].Name)
	}
}

// ---- ALTER TABLE ------------------------------------------------------------

func TestParseAlterTable_AddColumn(t *testing.T) {
	stmt := mustParse(t, "ALTER TABLE t ADD COLUMN email text")
	at := stmt.(AlterTableStmt)
	if at.TableName != "t" {
		t.Errorf("TableName: got %q", at.TableName)
	}
	if len(at.Actions) != 1 {
		t.Fatalf("Actions len: got %d", len(at.Actions))
	}
	a := at.Actions[0]
	if a.Kind != ActionAddColumn {
		t.Errorf("Kind: got %v", a.Kind)
	}
	if a.ColDef == nil || a.ColDef.DataType != "text" {
		t.Errorf("ColDef: %+v", a.ColDef)
	}
}

func TestParseAlterTable_DropColumn(t *testing.T) {
	stmt := mustParse(t, "ALTER TABLE t DROP COLUMN old_col")
	at := stmt.(AlterTableStmt)
	a := at.Actions[0]
	if a.Kind != ActionDropColumn || a.Column != "old_col" {
		t.Errorf("action: %+v", a)
	}
}

func TestParseAlterTable_AlterColumnType(t *testing.T) {
	stmt := mustParse(t, "ALTER TABLE t ALTER COLUMN price TYPE numeric(10,2)")
	at := stmt.(AlterTableStmt)
	a := at.Actions[0]
	if a.Kind != ActionAlterColumnType {
		t.Errorf("Kind: got %v", a.Kind)
	}
	if a.DataType != "numeric(10,2)" {
		t.Errorf("DataType: got %q", a.DataType)
	}
}

func TestParseAlterTable_SetDefault(t *testing.T) {
	stmt := mustParse(t, "ALTER TABLE t ALTER COLUMN status SET DEFAULT 'active'")
	at := stmt.(AlterTableStmt)
	a := at.Actions[0]
	if a.Kind != ActionSetDefault || a.Default != "'active'" {
		t.Errorf("action: %+v", a)
	}
}

func TestParseAlterTable_DropDefault(t *testing.T) {
	stmt := mustParse(t, "ALTER TABLE t ALTER COLUMN status DROP DEFAULT")
	at := stmt.(AlterTableStmt)
	a := at.Actions[0]
	if a.Kind != ActionDropDefault {
		t.Errorf("Kind: got %v", a.Kind)
	}
}

func TestParseAlterTable_SetNotNull(t *testing.T) {
	stmt := mustParse(t, "ALTER TABLE t ALTER COLUMN name SET NOT NULL")
	at := stmt.(AlterTableStmt)
	if at.Actions[0].Kind != ActionSetNotNull {
		t.Errorf("Kind: got %v", at.Actions[0].Kind)
	}
}

func TestParseAlterTable_DropNotNull(t *testing.T) {
	stmt := mustParse(t, "ALTER TABLE t ALTER COLUMN name DROP NOT NULL")
	at := stmt.(AlterTableStmt)
	if at.Actions[0].Kind != ActionDropNotNull {
		t.Errorf("Kind: got %v", at.Actions[0].Kind)
	}
}

func TestParseAlterTable_RenameColumn(t *testing.T) {
	stmt := mustParse(t, "ALTER TABLE t RENAME COLUMN old TO new")
	at := stmt.(AlterTableStmt)
	a := at.Actions[0]
	if a.Kind != ActionRenameColumn || a.Column != "old" || a.NewName != "new" {
		t.Errorf("action: %+v", a)
	}
}

func TestParseAlterTable_RenameTo(t *testing.T) {
	stmt := mustParse(t, "ALTER TABLE t RENAME TO t2")
	at := stmt.(AlterTableStmt)
	a := at.Actions[0]
	if a.Kind != ActionRenameTo || a.NewName != "t2" {
		t.Errorf("action: %+v", a)
	}
}

func TestParseAlterTable_AddConstraint(t *testing.T) {
	stmt := mustParse(t, "ALTER TABLE t ADD CONSTRAINT fk FOREIGN KEY (uid) REFERENCES users(id)")
	at := stmt.(AlterTableStmt)
	a := at.Actions[0]
	if a.Kind != ActionAddConstraint || a.Constraint.Name != "fk" {
		t.Errorf("action: %+v", a)
	}
}

func TestParseAlterTable_DropConstraint(t *testing.T) {
	stmt := mustParse(t, "ALTER TABLE t DROP CONSTRAINT fk")
	at := stmt.(AlterTableStmt)
	a := at.Actions[0]
	if a.Kind != ActionDropConstraint || a.Constraint.Name != "fk" {
		t.Errorf("action: %+v", a)
	}
}

func TestParseAlterTable_MultipleActions(t *testing.T) {
	stmt := mustParse(t, "ALTER TABLE t ADD COLUMN a int, ADD COLUMN b text")
	at := stmt.(AlterTableStmt)
	if len(at.Actions) != 2 {
		t.Fatalf("Actions len: got %d, want 2", len(at.Actions))
	}
}

// ---- DROP TABLE -------------------------------------------------------------

func TestParseDropTable(t *testing.T) {
	stmt := mustParse(t, "DROP TABLE users")
	dt := stmt.(DropTableStmt)
	if len(dt.TableNames) != 1 || dt.TableNames[0] != "users" || dt.IfExists {
		t.Errorf("%+v", dt)
	}
}

func TestParseDropTable_IfExists(t *testing.T) {
	stmt := mustParse(t, "DROP TABLE IF EXISTS users")
	dt := stmt.(DropTableStmt)
	if !dt.IfExists {
		t.Error("expected IfExists=true")
	}
}

func TestParseDropTable_MultipleNames(t *testing.T) {
	stmt := mustParse(t, "DROP TABLE a, b, c CASCADE")
	dt := stmt.(DropTableStmt)
	if len(dt.TableNames) != 3 {
		t.Fatalf("TableNames len: got %d, want 3", len(dt.TableNames))
	}
	if dt.TableNames[0] != "a" || dt.TableNames[1] != "b" || dt.TableNames[2] != "c" {
		t.Errorf("TableNames: %v", dt.TableNames)
	}
	if dt.IfExists {
		t.Error("IfExists should be false")
	}
}

// ---- CREATE INDEX -----------------------------------------------------------

func TestParseCreateIndex(t *testing.T) {
	stmt := mustParse(t, "CREATE INDEX idx_email ON users (email)")
	ci := stmt.(CreateIndexStmt)
	if ci.IndexName != "idx_email" || ci.TableName != "users" || ci.Unique {
		t.Errorf("%+v", ci)
	}
}

func TestParseCreateUniqueIndex(t *testing.T) {
	stmt := mustParse(t, "CREATE UNIQUE INDEX idx_email ON users (email)")
	ci := stmt.(CreateIndexStmt)
	if !ci.Unique {
		t.Error("expected Unique=true")
	}
}

func TestParseCreateIndex_Concurrently(t *testing.T) {
	stmt := mustParse(t, "CREATE INDEX CONCURRENTLY idx_name ON t (name)")
	ci := stmt.(CreateIndexStmt)
	if ci.IndexName != "idx_name" {
		t.Errorf("IndexName: %q", ci.IndexName)
	}
}

// ---- DROP INDEX -------------------------------------------------------------

func TestParseDropIndex(t *testing.T) {
	stmt := mustParse(t, "DROP INDEX idx_email")
	di := stmt.(DropIndexStmt)
	if di.IndexName != "idx_email" || di.IfExists {
		t.Errorf("%+v", di)
	}
}

func TestParseDropIndex_IfExists(t *testing.T) {
	stmt := mustParse(t, "DROP INDEX IF EXISTS idx_email")
	di := stmt.(DropIndexStmt)
	if !di.IfExists {
		t.Error("expected IfExists=true")
	}
}

// ---- CREATE SEQUENCE --------------------------------------------------------

func TestParseCreateSequence(t *testing.T) {
	stmt := mustParse(t, "CREATE SEQUENCE users_id_seq START 1")
	cs := stmt.(CreateSequenceStmt)
	if cs.SeqName != "users_id_seq" {
		t.Errorf("SeqName: %q", cs.SeqName)
	}
	if !strings.Contains(cs.Body, "START 1") {
		t.Errorf("Body: %q", cs.Body)
	}
}

// ---- DROP SEQUENCE ----------------------------------------------------------

func TestParseDropSequence(t *testing.T) {
	stmt := mustParse(t, "DROP SEQUENCE users_id_seq")
	ds := stmt.(DropSequenceStmt)
	if ds.SeqName != "users_id_seq" || ds.IfExists {
		t.Errorf("%+v", ds)
	}
}

func TestParseDropSequence_IfExists(t *testing.T) {
	stmt := mustParse(t, "DROP SEQUENCE IF EXISTS users_id_seq")
	ds := stmt.(DropSequenceStmt)
	if !ds.IfExists {
		t.Error("expected IfExists=true")
	}
}

// ---- CREATE TYPE ------------------------------------------------------------

func TestParseCreateTypeEnum(t *testing.T) {
	stmt := mustParse(t, "CREATE TYPE status AS ENUM ('active', 'inactive', 'pending')")
	ct := stmt.(CreateTypeStmt)
	if ct.TypeName != "status" {
		t.Errorf("TypeName: %q", ct.TypeName)
	}
	if len(ct.Labels) != 3 {
		t.Fatalf("Labels len: got %d, want 3", len(ct.Labels))
	}
	if ct.Labels[0] != "active" {
		t.Errorf("Labels[0]: %q", ct.Labels[0])
	}
}

func TestParseCreateTypeNonEnum_FallsBackToUnknown(t *testing.T) {
	stmt := mustParse(t, "CREATE TYPE address AS (street text, city text)")
	if _, ok := stmt.(UnknownStmt); !ok {
		t.Errorf("want UnknownStmt, got %T", stmt)
	}
}

// ---- Unknown ----------------------------------------------------------------

func TestParseUnknown(t *testing.T) {
	stmt := mustParse(t, "SET search_path = public")
	u, ok := stmt.(UnknownStmt)
	if !ok {
		t.Fatalf("want UnknownStmt, got %T", stmt)
	}
	if u.Raw != "SET search_path = public" {
		t.Errorf("Raw: %q", u.Raw)
	}
}

// ---- ALTER TABLE: unrecognized actions (ActionSkip) -------------------------

func TestParseAlterTable_UnrecognizedActionSkipped(t *testing.T) {
	cases := []string{
		"ALTER TABLE t SET SCHEMA myschema",
		"ALTER TABLE t SET TABLESPACE fast",
		"ALTER TABLE t CLUSTER ON idx",
		"ALTER TABLE t SET WITHOUT CLUSTER",
		"ALTER TABLE t ENABLE TRIGGER trg",
		"ALTER TABLE t DISABLE ROW LEVEL SECURITY",
		"ALTER TABLE t OWNER TO admin",
		"ALTER TABLE t VALIDATE CONSTRAINT fk",
		"ALTER TABLE t ATTACH PARTITION p FOR VALUES FROM (1) TO (100)",
		"ALTER TABLE t DETACH PARTITION p",
		"ALTER TABLE t ALTER COLUMN col SET STATISTICS 100",
		"ALTER TABLE t ALTER COLUMN col SET STORAGE EXTENDED",
	}
	for _, sql := range cases {
		stmt := mustParse(t, sql)
		at, ok := stmt.(AlterTableStmt)
		if !ok {
			t.Errorf("want AlterTableStmt for %q, got %T", sql, stmt)
			continue
		}
		if len(at.Actions) != 1 {
			t.Errorf("want 1 action for %q, got %d", sql, len(at.Actions))
			continue
		}
		if at.Actions[0].Kind != ActionSkip {
			t.Errorf("want ActionSkip for %q, got %v", sql, at.Actions[0].Kind)
		}
	}
}

// ---- ALTER INDEX ------------------------------------------------------------

func TestParseAlterIndex_RenameTo(t *testing.T) {
	stmt := mustParse(t, "ALTER INDEX idx_old RENAME TO idx_new")
	ai, ok := stmt.(AlterIndexStmt)
	if !ok {
		t.Fatalf("want AlterIndexStmt, got %T", stmt)
	}
	if ai.IndexName != "idx_old" || ai.NewName != "idx_new" {
		t.Errorf("%+v", ai)
	}
}

func TestParseAlterIndex_IfExists(t *testing.T) {
	stmt := mustParse(t, "ALTER INDEX IF EXISTS idx_old RENAME TO idx_new")
	ai, ok := stmt.(AlterIndexStmt)
	if !ok {
		t.Fatalf("want AlterIndexStmt, got %T", stmt)
	}
	if ai.IndexName != "idx_old" || ai.NewName != "idx_new" {
		t.Errorf("%+v", ai)
	}
}

func TestParseAlterIndex_OtherAction_FallsBackToUnknown(t *testing.T) {
	stmt := mustParse(t, "ALTER INDEX idx SET (fillfactor = 70)")
	if _, ok := stmt.(UnknownStmt); !ok {
		t.Errorf("want UnknownStmt, got %T", stmt)
	}
}

// ---- DROP TYPE --------------------------------------------------------------

func TestParseDropType(t *testing.T) {
	stmt := mustParse(t, "DROP TYPE status")
	dt, ok := stmt.(DropTypeStmt)
	if !ok {
		t.Fatalf("want DropTypeStmt, got %T", stmt)
	}
	if dt.TypeName != "status" || dt.IfExists {
		t.Errorf("%+v", dt)
	}
}

func TestParseDropType_IfExists(t *testing.T) {
	stmt := mustParse(t, "DROP TYPE IF EXISTS status")
	dt := stmt.(DropTypeStmt)
	if !dt.IfExists {
		t.Error("expected IfExists=true")
	}
	if dt.TypeName != "status" {
		t.Errorf("TypeName: %q", dt.TypeName)
	}
}

// ---- ALTER TYPE -------------------------------------------------------------

func TestParseAlterType_AddValue(t *testing.T) {
	stmt := mustParse(t, "ALTER TYPE status ADD VALUE 'pending'")
	at, ok := stmt.(AlterTypeStmt)
	if !ok {
		t.Fatalf("want AlterTypeStmt, got %T", stmt)
	}
	if at.TypeName != "status" {
		t.Errorf("TypeName: %q", at.TypeName)
	}
	if at.Action.Kind != AlterTypeAddValue {
		t.Errorf("Kind: %v", at.Action.Kind)
	}
	if at.Action.Value != "pending" {
		t.Errorf("Value: %q", at.Action.Value)
	}
	if at.Action.IfNotExists {
		t.Error("IfNotExists should be false")
	}
}

func TestParseAlterType_AddValueIfNotExists(t *testing.T) {
	stmt := mustParse(t, "ALTER TYPE status ADD VALUE IF NOT EXISTS 'new_val'")
	at := stmt.(AlterTypeStmt)
	if !at.Action.IfNotExists {
		t.Error("expected IfNotExists=true")
	}
	if at.Action.Value != "new_val" {
		t.Errorf("Value: %q", at.Action.Value)
	}
}

func TestParseAlterType_AddValueBefore(t *testing.T) {
	stmt := mustParse(t, "ALTER TYPE status ADD VALUE 'new' BEFORE 'old'")
	at := stmt.(AlterTypeStmt)
	if at.Action.Before != "old" {
		t.Errorf("Before: %q", at.Action.Before)
	}
	if at.Action.After != "" {
		t.Errorf("After should be empty: %q", at.Action.After)
	}
}

func TestParseAlterType_AddValueAfter(t *testing.T) {
	stmt := mustParse(t, "ALTER TYPE status ADD VALUE 'new' AFTER 'existing'")
	at := stmt.(AlterTypeStmt)
	if at.Action.After != "existing" {
		t.Errorf("After: %q", at.Action.After)
	}
}

func TestParseAlterType_RenameValue(t *testing.T) {
	stmt := mustParse(t, "ALTER TYPE status RENAME VALUE 'old' TO 'new'")
	at, ok := stmt.(AlterTypeStmt)
	if !ok {
		t.Fatalf("want AlterTypeStmt, got %T", stmt)
	}
	if at.Action.Kind != AlterTypeRenameValue {
		t.Errorf("Kind: %v", at.Action.Kind)
	}
	if at.Action.Value != "old" || at.Action.NewValue != "new" {
		t.Errorf("Value=%q NewValue=%q", at.Action.Value, at.Action.NewValue)
	}
}

func TestParseAlterType_RenameTo(t *testing.T) {
	stmt := mustParse(t, "ALTER TYPE old_type RENAME TO new_type")
	at, ok := stmt.(AlterTypeStmt)
	if !ok {
		t.Fatalf("want AlterTypeStmt, got %T", stmt)
	}
	if at.Action.Kind != AlterTypeRenameTo {
		t.Errorf("Kind: %v", at.Action.Kind)
	}
	if at.Action.NewName != "new_type" {
		t.Errorf("NewName: %q", at.Action.NewName)
	}
}

func TestParseAlterType_UnknownAction_FallsBackToUnknown(t *testing.T) {
	stmt := mustParse(t, "ALTER TYPE mytype SET SCHEMA newschema")
	if _, ok := stmt.(UnknownStmt); !ok {
		t.Errorf("want UnknownStmt, got %T", stmt)
	}
}

// ---- Generic CREATE objects -------------------------------------------------

func TestParseCreateView(t *testing.T) {
	stmt := mustParse(t, "CREATE VIEW v AS SELECT 1")
	co, ok := stmt.(CreateObjectStmt)
	if !ok {
		t.Fatalf("want CreateObjectStmt, got %T", stmt)
	}
	if co.Kind != ObjView {
		t.Errorf("Kind: %v", co.Kind)
	}
	if co.Name != "v" {
		t.Errorf("Name: %q", co.Name)
	}
	if co.OrReplace {
		t.Error("OrReplace should be false")
	}
}

func TestParseCreateOrReplaceView(t *testing.T) {
	stmt := mustParse(t, "CREATE OR REPLACE VIEW myview AS SELECT 1")
	co := stmt.(CreateObjectStmt)
	if !co.OrReplace {
		t.Error("expected OrReplace=true")
	}
	if co.Kind != ObjView {
		t.Errorf("Kind: %v", co.Kind)
	}
	if co.Name != "myview" {
		t.Errorf("Name: %q", co.Name)
	}
}

func TestParseCreateMaterializedView(t *testing.T) {
	stmt := mustParse(t, "CREATE MATERIALIZED VIEW mv AS SELECT 1")
	co := stmt.(CreateObjectStmt)
	if co.Kind != ObjMatView {
		t.Errorf("Kind: %v", co.Kind)
	}
	if co.Name != "mv" {
		t.Errorf("Name: %q", co.Name)
	}
}

func TestParseCreateSchema(t *testing.T) {
	stmt := mustParse(t, "CREATE SCHEMA myschema")
	co := stmt.(CreateObjectStmt)
	if co.Kind != ObjSchema || co.Name != "myschema" {
		t.Errorf("%+v", co)
	}
}

func TestParseCreateExtension(t *testing.T) {
	stmt := mustParse(t, "CREATE EXTENSION IF NOT EXISTS pg_trgm")
	co := stmt.(CreateObjectStmt)
	if co.Kind != ObjExtension || co.Name != "pg_trgm" {
		t.Errorf("%+v", co)
	}
}

func TestParseCreateFunction(t *testing.T) {
	stmt := mustParse(t, "CREATE FUNCTION myfunc(x int) RETURNS int AS $$ SELECT x $$ LANGUAGE sql")
	co := stmt.(CreateObjectStmt)
	if co.Kind != ObjFunction || co.Name != "myfunc" {
		t.Errorf("%+v", co)
	}
}

func TestParseCreateOrReplaceFunction(t *testing.T) {
	stmt := mustParse(t, "CREATE OR REPLACE FUNCTION myfunc() RETURNS void AS $$ $$ LANGUAGE sql")
	co := stmt.(CreateObjectStmt)
	if !co.OrReplace {
		t.Error("expected OrReplace=true")
	}
	if co.Kind != ObjFunction || co.Name != "myfunc" {
		t.Errorf("%+v", co)
	}
}

func TestParseCreateProcedure(t *testing.T) {
	stmt := mustParse(t, "CREATE PROCEDURE myproc() LANGUAGE sql AS $$ $$")
	co := stmt.(CreateObjectStmt)
	if co.Kind != ObjProcedure || co.Name != "myproc" {
		t.Errorf("%+v", co)
	}
}

func TestParseCreateTrigger(t *testing.T) {
	stmt := mustParse(t, "CREATE TRIGGER my_trigger AFTER INSERT ON users FOR EACH ROW EXECUTE FUNCTION f()")
	co := stmt.(CreateObjectStmt)
	if co.Kind != ObjTrigger {
		t.Errorf("Kind: %v", co.Kind)
	}
	// name should be "my_trigger_on_users"
	if co.Name != "my_trigger_on_users" {
		t.Errorf("Name: %q", co.Name)
	}
}

func TestParseCreateConstraintTrigger(t *testing.T) {
	stmt := mustParse(t, "CREATE CONSTRAINT TRIGGER ctrg AFTER INSERT ON orders FOR EACH ROW EXECUTE FUNCTION f()")
	co := stmt.(CreateObjectStmt)
	if co.Kind != ObjTrigger {
		t.Errorf("Kind: %v", co.Kind)
	}
	if co.Name != "ctrg_on_orders" {
		t.Errorf("Name: %q", co.Name)
	}
}

func TestParseCreateDomain(t *testing.T) {
	stmt := mustParse(t, "CREATE DOMAIN posint AS integer CHECK (VALUE > 0)")
	co := stmt.(CreateObjectStmt)
	if co.Kind != ObjDomain || co.Name != "posint" {
		t.Errorf("%+v", co)
	}
}

func TestParseCreatePolicy(t *testing.T) {
	stmt := mustParse(t, "CREATE POLICY p1 ON users USING (user_id = current_user_id())")
	co := stmt.(CreateObjectStmt)
	if co.Kind != ObjPolicy {
		t.Errorf("Kind: %v", co.Kind)
	}
	if co.Name != "p1_on_users" {
		t.Errorf("Name: %q", co.Name)
	}
}

func TestParseCreateRule(t *testing.T) {
	stmt := mustParse(t, "CREATE RULE r1 AS ON INSERT TO myview DO INSTEAD NOTHING")
	co := stmt.(CreateObjectStmt)
	if co.Kind != ObjRule {
		t.Errorf("Kind: %v", co.Kind)
	}
	if co.Name != "r1_on_myview" {
		t.Errorf("Name: %q", co.Name)
	}
}

// ---- Generic DROP objects ---------------------------------------------------

func TestParseDropView(t *testing.T) {
	stmt := mustParse(t, "DROP VIEW IF EXISTS myview")
	do, ok := stmt.(DropObjectStmt)
	if !ok {
		t.Fatalf("want DropObjectStmt, got %T", stmt)
	}
	if do.Kind != ObjView || do.Name != "myview" || !do.IfExists {
		t.Errorf("%+v", do)
	}
}

func TestParseDropMaterializedView(t *testing.T) {
	stmt := mustParse(t, "DROP MATERIALIZED VIEW mv")
	do := stmt.(DropObjectStmt)
	if do.Kind != ObjMatView || do.Name != "mv" || do.IfExists {
		t.Errorf("%+v", do)
	}
}

func TestParseDropSchema(t *testing.T) {
	stmt := mustParse(t, "DROP SCHEMA IF EXISTS s1")
	do := stmt.(DropObjectStmt)
	if do.Kind != ObjSchema || do.Name != "s1" || !do.IfExists {
		t.Errorf("%+v", do)
	}
}

func TestParseDropExtension(t *testing.T) {
	stmt := mustParse(t, "DROP EXTENSION pg_trgm")
	do := stmt.(DropObjectStmt)
	if do.Kind != ObjExtension || do.Name != "pg_trgm" {
		t.Errorf("%+v", do)
	}
}

func TestParseDropFunction(t *testing.T) {
	stmt := mustParse(t, "DROP FUNCTION IF EXISTS myfunc(int)")
	do := stmt.(DropObjectStmt)
	if do.Kind != ObjFunction || do.Name != "myfunc" || !do.IfExists {
		t.Errorf("%+v", do)
	}
}

func TestParseDropProcedure(t *testing.T) {
	stmt := mustParse(t, "DROP PROCEDURE myproc")
	do := stmt.(DropObjectStmt)
	if do.Kind != ObjProcedure || do.Name != "myproc" {
		t.Errorf("%+v", do)
	}
}

func TestParseDropTrigger(t *testing.T) {
	stmt := mustParse(t, "DROP TRIGGER IF EXISTS my_trigger ON users")
	do := stmt.(DropObjectStmt)
	if do.Kind != ObjTrigger || !do.IfExists {
		t.Errorf("%+v", do)
	}
	if do.Name != "my_trigger_on_users" {
		t.Errorf("Name: %q", do.Name)
	}
}

func TestParseDropDomain(t *testing.T) {
	stmt := mustParse(t, "DROP DOMAIN posint")
	do := stmt.(DropObjectStmt)
	if do.Kind != ObjDomain || do.Name != "posint" {
		t.Errorf("%+v", do)
	}
}

func TestParseDropPolicy(t *testing.T) {
	stmt := mustParse(t, "DROP POLICY p1 ON users")
	do := stmt.(DropObjectStmt)
	if do.Kind != ObjPolicy || do.Name != "p1_on_users" {
		t.Errorf("%+v", do)
	}
}

func TestParseDropRule(t *testing.T) {
	stmt := mustParse(t, "DROP RULE r1 ON myview")
	do := stmt.(DropObjectStmt)
	if do.Kind != ObjRule || do.Name != "r1_on_myview" {
		t.Errorf("%+v", do)
	}
}

// ---- ALTER SEQUENCE ---------------------------------------------------------

func TestParseAlterSequence_RenameTo(t *testing.T) {
	stmt := mustParse(t, "ALTER SEQUENCE seq RENAME TO seq2")
	as := stmt.(AlterSequenceStmt)
	if as.SeqName != "seq" || as.NewName != "seq2" {
		t.Errorf("%+v", as)
	}
}

func TestParseAlterSequence_IfExists_RenameTo(t *testing.T) {
	stmt := mustParse(t, "ALTER SEQUENCE IF EXISTS myseq RENAME TO newseq")
	as := stmt.(AlterSequenceStmt)
	if as.SeqName != "myseq" || as.NewName != "newseq" {
		t.Errorf("%+v", as)
	}
}

func TestParseAlterSequence_OtherAction_PassThrough(t *testing.T) {
	stmt := mustParse(t, "ALTER SEQUENCE seq RESTART WITH 1")
	if _, ok := stmt.(UnknownStmt); !ok {
		t.Errorf("expected UnknownStmt, got %T", stmt)
	}
}

// ---- ALTER <object> RENAME TO -----------------------------------------------

func TestParseAlterView_RenameTo(t *testing.T) {
	stmt := mustParse(t, "ALTER VIEW myview RENAME TO newview")
	ao := stmt.(AlterObjectStmt)
	if ao.Kind != ObjView || ao.OldName != "myview" || ao.NewName != "newview" {
		t.Errorf("%+v", ao)
	}
}

func TestParseAlterMatView_RenameTo(t *testing.T) {
	stmt := mustParse(t, "ALTER MATERIALIZED VIEW mv RENAME TO mv2")
	ao := stmt.(AlterObjectStmt)
	if ao.Kind != ObjMatView || ao.OldName != "mv" || ao.NewName != "mv2" {
		t.Errorf("%+v", ao)
	}
}

func TestParseAlterSchema_RenameTo(t *testing.T) {
	stmt := mustParse(t, "ALTER SCHEMA s1 RENAME TO s2")
	ao := stmt.(AlterObjectStmt)
	if ao.Kind != ObjSchema || ao.OldName != "s1" || ao.NewName != "s2" {
		t.Errorf("%+v", ao)
	}
}

func TestParseAlterFunction_RenameTo(t *testing.T) {
	stmt := mustParse(t, "ALTER FUNCTION myfunc(integer) RENAME TO myfunc2")
	ao := stmt.(AlterObjectStmt)
	if ao.Kind != ObjFunction || ao.OldName != "myfunc" || ao.NewName != "myfunc2" {
		t.Errorf("%+v", ao)
	}
}

func TestParseAlterDomain_RenameTo(t *testing.T) {
	stmt := mustParse(t, "ALTER DOMAIN posint RENAME TO positive_int")
	ao := stmt.(AlterObjectStmt)
	if ao.Kind != ObjDomain || ao.OldName != "posint" || ao.NewName != "positive_int" {
		t.Errorf("%+v", ao)
	}
}

func TestParseAlterTrigger_RenameTo(t *testing.T) {
	stmt := mustParse(t, "ALTER TRIGGER trg ON users RENAME TO trg2")
	ao := stmt.(AlterObjectStmt)
	if ao.Kind != ObjTrigger || ao.OldName != "trg_on_users" || ao.NewName != "trg2_on_users" {
		t.Errorf("%+v", ao)
	}
}

func TestParseAlterPolicy_RenameTo(t *testing.T) {
	stmt := mustParse(t, "ALTER POLICY p1 ON orders RENAME TO p2")
	ao := stmt.(AlterObjectStmt)
	if ao.Kind != ObjPolicy || ao.OldName != "p1_on_orders" || ao.NewName != "p2_on_orders" {
		t.Errorf("%+v", ao)
	}
}

func TestParseAlterView_OtherAction_PassThrough(t *testing.T) {
	stmt := mustParse(t, "ALTER VIEW myview SET (security_barrier=on)")
	if _, ok := stmt.(UnknownStmt); !ok {
		t.Errorf("expected UnknownStmt, got %T", stmt)
	}
}
